### ISSUE TITLE
minting fails if mint endpoint takes more than 5000 ms

### ISSUE THREAD

**Issue by yongjun-chee** [tatumio/woocommerce-plugin#13]
After minting several tokens, I've run into several error cases when the `v3/nft/mint` api takes more than 5000 ms to respond.
Could you fix or pinpoint to where this plugin is making call to minting api endpoint?
![Screen Shot 2022-02-22 at 10 53 19 AM](https://user-images.githubusercontent.com/4030909/155169751-d37899a9-8b99-466d-98f7-88280632ff2a.png)

**Comment by Hathoriel** [comment]
Hi, yes I know about the issue. Thank you for adding it, I will process it
soon.

Dne út 22. 2. 2022 16:58 uživatel Yong Chee ***@***.***>
napsal:

**Comment by Hathoriel** [comment]
Hi @yongjun-chee, this issue should be fixed in commit https://github.com/tatumio/wordpress-plugin/commit/b653188658722f9067769c5f5e9e372ca54000d2 and version 2.0.24

**Comment by yongjun-chee** [comment]
Thanks!
Just confirmed that API respond time of 5642 ms didn't error out with this 2.0.24 version.

**Comment by Hathoriel** [comment]
Nice, I am happy this works! :-)
