### ISSUE TITLE
NFT Picture not Showing on OpenSea Testnet 

### ISSUE THREAD

**Issue by nickweisser** [tatumio/woocommerce-plugin#19]
Hi there, have installed the NFT Maker plugin and minted a first test NFT on the Polygon Mumbai testnet. It went all very smooth, only the [picture](https://testnets.opensea.io/de-DE/assets/mumbai/0xcd2ada00c48a27faa5cc67f9a1ed55b89ddf7f77/1000508000000000) seems to not be displayed. Here's the [WooCommerce product](https://wapuu-nft.openstream.ch/index.php/product/swiss-army-knife-wapuu-2015-test/).

Ted mentioned on the Discord that this is a known issue in both test and main net and has to do with how OpenSea functions that Tatum is not able to resolve this as the issue is on their end. I was able to mint an [NFT](https://testnets.opensea.io/de-DE/assets/mumbai/0xcd2ada00c48a27faa5cc67f9a1ed55b89ddf7f77/1009229000000000
) from the Tatum dashboard (NFT Minter), though, that I see the image for. 

Any additional insights in this regard would be very helpful as I'm trying to launch the Swiss Wapuu NFT Collection for [WordCamp Switzerland](https://switzerland.wordcamp.org/2023/) on April 1st. Not an Aprils' fool.

**Comment by Smrecz** [comment]
Issue outdated, please re-open if still relevant.
