### ISSUE TITLE
Getting Invalid payment method

### ISSUE THREAD

**Issue by tarex** [tatumio/woocommerce-plugin#3]
Can you please guide which payment method we need to select to ignore that message from checkout? By default, we haven't selected any. I'm trying to use it with testnet from local. 
![Screen Shot 2022-01-02 at 9 45 36 PM](https://user-images.githubusercontent.com/1109422/147881134-5ae29014-82c0-40b9-a755-e796ad05a1e8.png)

**Comment by Hathoriel** [comment]
Hi, the plugin works only with Mainnet.
